name: Run Tests and Linter

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: flowcheck install dependencies & run code checkers
        uses: keygun-development/FlowCheck@v3.0.1
        with:
          enableTests: true
          enableLinter: true
          testCommand: 'composer run test'
          lintCommand: 'npm run build'
